# Generated by Django 5.1.6 on 2025-03-19 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_payrollassignment_education_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollassignment',
            name='is_terminated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='payrollassignment',
            name='benefits_type1',
            field=models.CharField(blank=True, choices=[('Eligible', 'Eligible'), ('Not Eligible', 'Not Eligible'), ('Insurance', 'Insurance')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='payrollassignment',
            name='benefits_type2',
            field=models.CharField(blank=True, choices=[('Eligible', 'Eligible'), ('Not Eligible', 'Not Eligible'), ('Insurance', 'Insurance')], max_length=30, null=True),
        ),
    ]
