# Generated by Django 5.1.6 on 2025-02-20 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_accs_groups_user_accs_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_accs',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user_accs',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('banned', 'banned')], default='active', max_length=20),
        ),
        migrations.DeleteModel(
            name='address',
        ),
    ]
