# Generated by Django 5.1.6 on 2025-03-12 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_user_id_payrollassignment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollassignment',
            name='budget_change_effective_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payrollassignment',
            name='current_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='payrollassignment',
            name='from_fte',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='payrollassignment',
            name='from_speed_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='payrollassignment',
            name='fte_change_effective_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payrollassignment',
            name='job_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payrollassignment',
            name='new_pay_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='payrollassignment',
            name='other_specification',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payrollassignment',
            name='pay_rate_change_effective_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payrollassignment',
            name='pay_rate_change_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payrollassignment',
            name='position_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='payrollassignment',
            name='reallocation_dates',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payrollassignment',
            name='reallocation_from_position',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='payrollassignment',
            name='reallocation_to_position',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='payrollassignment',
            name='termination_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payrollassignment',
            name='termination_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payrollassignment',
            name='to_fte',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='payrollassignment',
            name='to_speed_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='PayrollChange',
        ),
    ]
