# Generated by Django 5.1.6 on 2025-03-15 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_payrollassignment_budget_change_effective_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReimbursementRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=100)),
                ('employee_id', models.CharField(max_length=50)),
                ('today_date', models.DateField()),
                ('reimbursement_items', models.TextField()),
                ('purpose', models.TextField()),
                ('meal_info', models.TextField(blank=True, null=True)),
                ('cost_center_1', models.CharField(max_length=50)),
                ('amount_1', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_center_2', models.CharField(blank=True, max_length=50, null=True)),
                ('amount_2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_reimbursement', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('signature_url', models.URLField(blank=True, null=True)),
                ('approve_date', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
