# Generated by Django 5.1.6 on 2025-03-16 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_reimbursementrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reimbursementrequest',
            name='amount_1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='reimbursementrequest',
            name='cost_center_1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reimbursementrequest',
            name='employee_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reimbursementrequest',
            name='employee_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reimbursementrequest',
            name='purpose',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reimbursementrequest',
            name='reimbursement_items',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reimbursementrequest',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled')], default='Draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='reimbursementrequest',
            name='today_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reimbursementrequest',
            name='total_reimbursement',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
