# Generated by Django 5.1.6 on 2025-03-16 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_reimbursementrequest_amount_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reimbursementrequest',
            name='pdf_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='reimbursementrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'Pending')), fields=('user',), name='unique_pending_reimbursement_per_user'),
        ),
    ]
