# Generated by Django 5.1.6 on 2025-03-16 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_reimbursementrequest_pdf_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='positioninformation',
            name='benefits_type',
        ),
        migrations.AddField(
            model_name='payrollassignment',
            name='number_of_positions',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='payrollassignment',
            name='pdf_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='positioninformation',
            name='benefit_type',
            field=models.CharField(blank=True, choices=[('Benefits Eligible', 'Benefits Eligible'), ('Non-Benefits Eligible', 'Non-Benefits Eligible'), ('Insurance Only', 'Insurance Only')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='payrollassignment',
            name='current_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='payrollassignment',
            name='from_fte',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='payrollassignment',
            name='new_pay_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='payrollassignment',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='payrollassignment',
            name='to_fte',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='positioninformation',
            name='budget_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='positioninformation',
            name='fte',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='positioninformation',
            name='salary_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
