# Generated by Django 5.1.6 on 2025-03-16 20:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_positioninformation_benefits_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positioninformation',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
