# Generated by Django 5.1.6 on 2025-03-17 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_positioninformation_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payrollassignment',
            name='number_of_positions',
        ),
        migrations.AddField(
            model_name='payrollassignment',
            name='benefits_type1',
            field=models.CharField(blank=True, choices=[('eligible', 'Eligible'), ('no_eligible', 'Not Eligible'), ('insurance', 'Insurance')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='payrollassignment',
            name='benefits_type2',
            field=models.CharField(blank=True, choices=[('eligible', 'Eligible'), ('no_eligible', 'Not Eligible'), ('insurance', 'Insurance')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='payrollassignment',
            name='budget_percentage1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='payrollassignment',
            name='budget_percentage2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='payrollassignment',
            name='end_date1',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payrollassignment',
            name='end_date2',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payrollassignment',
            name='fte1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='payrollassignment',
            name='fte2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='payrollassignment',
            name='pcn1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='payrollassignment',
            name='pcn2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='payrollassignment',
            name='position_title1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payrollassignment',
            name='position_title2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payrollassignment',
            name='salary1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='payrollassignment',
            name='salary2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='payrollassignment',
            name='salary_fte1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='payrollassignment',
            name='speed_type1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='payrollassignment',
            name='speed_type2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='payrollassignment',
            name='start_date1',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payrollassignment',
            name='start_date2',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payrollassignment',
            name='current_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='payrollassignment',
            name='from_fte',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='payrollassignment',
            name='new_pay_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='payrollassignment',
            name='to_fte',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.DeleteModel(
            name='PositionInformation',
        ),
    ]
